# Generated by Django 2.2.13 on 2020-09-16 10:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_job_jobskills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseskills',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='jobskills',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('created',)},
        ),
        migrations.CreateModel(
            name='JobPostings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('median_salary', models.FloatField(help_text='The median annual salary advertised on job postings for the job.')),
                ('median_posting_duration', models.IntegerField(help_text='The median duration of closed job postings. Duration is measured in days.')),
                ('unique_postings', models.IntegerField(help_text='The number of unique monthly active job postings.')),
                ('unique_companies', models.IntegerField(help_text='The number of unique companies represented in your filtered set of postings.')),
                ('job', models.ForeignKey(help_text='The ID of the job to filter job postings by.', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Job')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
