# Generated by Django 2.2.17 on 2021-01-22 00:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_auto_20210113_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedCourseSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', models.CharField(help_text='The course key belonging the course whose skill needs to be black-listed.', max_length=255)),
                ('skill', models.ForeignKey(help_text='The skill extracted for the course that needs to be black-listed.', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Skill')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
