# Generated by Django 2.2.17 on 2021-01-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0005_blacklistedcourseskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseskills',
            name='is_blacklisted',
            field=models.BooleanField(default=False, help_text='Blacklist this course skill, useful to handle false positives.'),
        ),
        migrations.DeleteModel(
            name='BlacklistedCourseSkill',
        ),
    ]
