# Generated by Django 2.2.17 on 2021-02-09 01:52

from django.db import migrations

from taxonomy.migrations_utils import delete_all_records


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0006_auto_20210128_0135'),
    ]

    operations = [
        migrations.RunPython(delete_all_records),
    ]
