# Generated by Django 2.2.18 on 2021-02-16 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0007_delete_all_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='external_id',
            field=models.CharField(default=None, help_text='The external identifier for the job received from API.', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='job',
            field=models.ForeignKey(help_text='The ID of the job to filter job postings by.', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Job', unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='external_id',
            field=models.CharField(help_text='The external identifier for the skill received from API.', max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='courseskills',
            unique_together={('course_id', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='jobskills',
            unique_together={('job', 'skill')},
        ),
    ]
