# Generated by Django 2.2.18 on 2021-02-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0008_auto_20210216_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, default='', help_text='A short description for the skill received from API.'),
        ),
    ]
