# Generated by Django 2.2.20 on 2021-04-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0009_skill_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseskills',
            options={'ordering': ('created',), 'verbose_name': 'Course Skill', 'verbose_name_plural': 'Course Skills'},
        ),
        migrations.AddField(
            model_name='courseskills',
            name='course_key',
            field=models.CharField(blank=True, editable=False, help_text='The key of the course whose text was used for skills extraction.', max_length=255, null=True),
        ),
    ]
