# Generated by Django 2.2.20 on 2021-04-15 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0012_auto_20210412_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseskills',
            name='course_id',
        ),
    ]
