# Generated by Django 2.2.20 on 2021-04-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0013_remove_courseskills_course_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpostings',
            options={'ordering': ('created',), 'verbose_name': 'Job Posting', 'verbose_name_plural': 'Job Postings'},
        ),
        migrations.AlterModelOptions(
            name='jobskills',
            options={'ordering': ('created',), 'verbose_name': 'Job Skill', 'verbose_name_plural': 'Job Skills'},
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='median_salary',
            field=models.FloatField(help_text='The median annual salary (in USD) advertised on job postings for the job.'),
        ),
    ]
