# Generated by Django 2.2.20 on 2021-10-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0014_auto_20210416_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(help_text='The title of job.', max_length=255, null=True, unique=True),
        ),
    ]
