# Generated by Django 2.2.27 on 2022-02-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0016_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostings',
            name='median_posting_duration',
            field=models.IntegerField(blank=True, help_text='The median duration of closed job postings. Duration is measured in days.', null=True),
        ),
    ]
