# Generated by Django 3.2.12 on 2022-06-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0018_auto_20220613_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostings',
            name='median_salary',
            field=models.FloatField(blank=True, help_text='The median annual salary (in USD) advertised on job postings for the job.', null=True),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='unique_companies',
            field=models.IntegerField(blank=True, help_text='The number of unique companies represented in your filtered set of postings.', null=True),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='unique_postings',
            field=models.IntegerField(blank=True, help_text='The number of unique monthly active job postings.', null=True),
        ),
    ]
