# Generated by Django 3.2.15 on 2022-09-06 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0023_refreshprogramskillsconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refreshprogramskillsconfig',
            options={'verbose_name': 'Refresh Program Skills Configuration'},
        ),
    ]
