# Generated by Django 3.2.18 on 2023-03-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0029_xblock_refresh_argmuments_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsquiz',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='taxonomy.Skill'),
        ),
    ]
