# Generated by Django 3.2.20 on 2023-09-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0033_b2c_allowlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xblockskills',
            name='usage_key',
            field=models.CharField(db_index=True, help_text='The key of the xblock whose text was used for skills extraction.', max_length=255, unique=True),
        ),
    ]
