# Generated by Django 2.2.17 on 2021-03-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0009_skill_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, db_index=True, help_text='The name of the skill.', max_length=255),
        ),
    ]
