# Generated by Django 3.2.15 on 2022-08-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0022_auto_20220825_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshProgramSkillsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arguments', models.TextField(blank=True, default='', help_text='Useful for manually running a Jenkins job. Specify like "--program=uuid --program=uuid".')),
            ],
            options={
                'verbose_name': 'refresh_program_skills argument',
            },
        ),
    ]
