# Generated by Django 3.2.16 on 2022-12-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0028_xblock_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshXBlockSkillsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arguments', models.TextField(blank=True, default='', help_text='Useful for manually running a Jenkins job. Specify like "--course=key1 --course=key2".')),
            ],
            options={
                'verbose_name': 'refresh_xblock_skills argument',
            },
        ),
    ]
