# Generated by Django 3.2.19 on 2023-05-08 14:28

import django.utils.timezone
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0031_auto_20230417_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRunXBlockSkillsTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_run_key', models.CharField(help_text='The key of the course run.', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Course run xblock skills tracker',
                'verbose_name_plural': 'Course run xblock skills tracker',
                'ordering': ('created',),
            },
        ),
        migrations.AlterModelOptions(
            name='jobpath',
            options={'ordering': ('created',), 'verbose_name': 'Job Path Description', 'verbose_name_plural': 'Job Path Descriptions'},
        ),
    ]
