# Generated by Django 3.2.18 on 2023-06-15 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0032_auto_20230508_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserunxblockskillstracker',
            name='course_run_key',
            field=models.CharField(help_text='Course run key of the course under which all xblocks were tagged.', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='B2CJobAllowList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(help_text='The job to add to the allowlist for B2C Job listings.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='taxonomy.job', to_field='external_id')),
            ],
            options={
                'verbose_name': 'B2C Job Allow List entry',
                'verbose_name_plural': 'B2C Job Allow List entries',
            },
        ),
    ]
