# Generated by Django 4.2.16 on 2026-01-27 04:59

import django.utils.timezone
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0038_mariadb_uuid_conversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('external_id', models.CharField(db_index=True, help_text='EMSI external ID (e.g., ET1234567890, ES1234567890, IN123)', max_length=255)),
                ('content_type', models.CharField(choices=[('job', 'Job'), ('skill', 'Skill'), ('industry', 'Industry')], db_index=True, help_text='Type of entity being translated (job, skill, or industry)', max_length=50)),
                ('language_code', models.CharField(db_index=True, help_text='Target language code (e.g., es, ar, fr) following ISO 639-1', max_length=10)),
                ('title', models.CharField(help_text='Translated name/title of the entity', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Translated description field')),
                ('source_hash', models.CharField(help_text='MD5 hash of English source text (title + description). Used to detect when source content changes and retranslation is needed.', max_length=64)),
            ],
            options={
                'verbose_name': 'Taxonomy Translation',
                'verbose_name_plural': 'Taxonomy Translations',
                'indexes': [models.Index(fields=['language_code', 'content_type'], name='taxonomy_ta_languag_ce278d_idx'), models.Index(fields=['external_id', 'language_code'], name='taxonomy_ta_externa_b71780_idx')],
                'unique_together': {('external_id', 'content_type', 'language_code')},
            },
        ),
    ]
